# Generated by Django 4.2.13 on 2024-06-02 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Ayol'), (1, 'Erkak')], default=1, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam quyidagi formatda kiririlishi shart: '+9989999999'. 15 ta raqamdan ziyodini qo'llab quvvatlaydi.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqami'),
        ),
    ]
