# Generated by Django 4.2.13 on 2024-05-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0003_alter_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='UZS da kiritilsin', max_digits=15, verbose_name='miqdor')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('payed_at', models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqt")),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': "Hodimlarning oylik maoshi to'lovi",
                'verbose_name_plural': "Hodimlarning oylik maoshi to'lovlari",
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='UZS da kiritilsin', max_digits=15, verbose_name='miqdor')),
                ('description', models.TextField(help_text='Jarima berilish sabablari yoziladi', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan vaqt')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='UZS da kiritilsin', max_digits=15, verbose_name='miqdor')),
                ('description', models.TextField(help_text='KPI berilish sabablari yoziladi', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan vaqt')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
            },
        ),
    ]
