# Generated by Django 4.2.13 on 2024-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('lef_at', models.DateTimeField(auto_now_add=True, verbose_name="Bo'shatilgan vaqti")),
            ],
            options={
                'verbose_name': "Ishdan bo'shagan xodim",
                'verbose_name_plural': "Ishdan bo'shagan xodimlar",
            },
        ),
    ]
