# Generated by Django 4.2.13 on 2024-05-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_rename_saff_id_staffleaving_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffleaving',
            old_name='lef_at',
            new_name='left_at',
        ),
    ]
