# Generated by Django 4.2.13 on 2024-05-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_ttj_options_alter_staff_ttj_id'),
        ('actions', '0005_attandance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='ttj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.ttj', verbose_name='ТЦ'),
        ),
    ]
