# Generated by Django 4.2.13 on 2024-06-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_ttj_options_alter_staff_role_and_more'),
        ('actions', '0006_alter_attandance_ttj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='ttj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.ttj', verbose_name='Bino'),
        ),
    ]
