# Generated by Django 4.2.13 on 2024-05-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('passport', models.FileField(upload_to='Staff/passport', verbose_name='Passport nusxasi')),
                ('salary', models.DecimalField(decimal_places=2, help_text='UZS da kiritilsin', max_digits=15, verbose_name='Maosh')),
                ('image', models.ImageField(help_text='3X4 rasm yuklansin', upload_to='Staff/image3x4', verbose_name='rasm')),
                ('role', models.IntegerField(choices=[(1, 'Mudir'), (2, 'Tarbiyachi'), (3, 'Qorovul'), (4, 'Hamshira'), (5, 'Farrosh')], default=3, verbose_name='Hodim turi')),
                ('is_working', models.BooleanField(default=True, verbose_name='Ishlayotganlik statusi')),
                ('description', models.TextField(help_text="Qo'shimcha izohlar uchun. Hodim nima ish qilishi va ho kazo larni kiritsa bo'ladi", verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
            bases=('account.customuser',),
        ),
        migrations.CreateModel(
            name='Ttj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nomi')),
                ('university', models.CharField(max_length=250, verbose_name='Universitet')),
                ('address', models.CharField(max_length=250, verbose_name='Mazili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Dasturga qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Talabalar turar joyi',
                'verbose_name_plural': 'Talabalar turar joylari',
            },
        ),
    ]
