# Generated by Django 4.2.13 on 2024-05-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_alter_staff_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttj',
            options={'verbose_name': 'торговые центр', 'verbose_name_plural': 'торговые центры'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='ttj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.ttj', verbose_name='ТЦ'),
        ),
    ]
