# Generated by Django 4.2.13 on 2024-06-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_ttj_options_alter_staff_ttj_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttj',
            options={'verbose_name': 'Bino', 'verbose_name_plural': 'Binolar'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(1, 'Mudir'), (2, 'Tarbiyachi'), (3, 'Qorovul'), (4, 'Hamshira'), (5, 'Farrosh'), (6, 'Hisobchi'), (7, 'Biznes egasi')], default=3, verbose_name='Hodim turi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ttj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.ttj', verbose_name='Bino'),
        ),
        migrations.AlterField(
            model_name='ttj',
            name='university',
            field=models.CharField(max_length=250, verbose_name='Hamkor tashkilot'),
        ),
    ]
